import React, { useEffect, useRef } from 'react';
import { UserProfile } from '../../types';
import { CoinIcon } from '../CoinIcon';

interface AppHeaderProps { userProfile: UserProfile; isAuthenticated: boolean; onHomeClick: () => void; onLoginClick: () => void; onLogoutClick: () => void; onProfileClick?: () => void; onShopClick?: () => void; onAdminClick?: () => void; onAdultRoomClick?: () => void; onDictionaryStudioClick?: () => void; }
const navButton = 'hidden rounded-xl px-3 py-2 text-sm font-black transition hover:bg-indigo-50 md:block';

export const AppHeader: React.FC<AppHeaderProps> = ({ userProfile, isAuthenticated, onHomeClick, onLoginClick, onLogoutClick, onProfileClick, onShopClick, onAdminClick, onAdultRoomClick, onDictionaryStudioClick }) => {
  const isAdmin = userProfile.role === 'admin';
  const isParent = userProfile.role === 'parent' || userProfile.accountMode === 'parent';
  const isTeacher = userProfile.role === 'teacher' || userProfile.accountMode === 'teacher';
  const isPractice = isAuthenticated && !isParent && !isTeacher;
  const premiumActive = isAdmin || (userProfile.subscriptionTier === 'premium' && (!userProfile.premiumExpiresAt || Date.parse(userProfile.premiumExpiresAt) > Date.now()));
  const hasDictionaryStudio = isTeacher || isAdmin || (isPractice && premiumActive) || isParent;
  const showKidsEconomy = isAuthenticated && isParent;
  const modeLabel = isTeacher ? 'Teacher' : isParent ? 'Kids' : isPractice ? 'Practice' : 'AnnWord';
  const profileLabel = isTeacher ? 'Профиль преподавателя' : isParent ? 'Профиль ребёнка' : 'Статистика';
  const cabinetLabel = isTeacher ? 'Ученики' : 'Кабинет родителя';
  const accountMenuRef = useRef<HTMLDetailsElement>(null);

  useEffect(() => { const close = (event: PointerEvent) => { if (!accountMenuRef.current?.contains(event.target as Node)) accountMenuRef.current?.removeAttribute('open'); }; const esc = (event: KeyboardEvent) => { if (event.key === 'Escape') accountMenuRef.current?.removeAttribute('open'); }; document.addEventListener('pointerdown', close); document.addEventListener('keydown', esc); return () => { document.removeEventListener('pointerdown', close); document.removeEventListener('keydown', esc); }; }, []);
  const go = (callback?: () => void) => { accountMenuRef.current?.removeAttribute('open'); callback?.(); };

  return <header className="sticky top-0 z-40 flex w-full items-center justify-between gap-2 border-b border-indigo-50 bg-white/85 px-3 py-2.5 backdrop-blur sm:gap-3 sm:px-4 sm:py-3">
    <div className="flex min-w-0 items-center gap-2"><button type="button" onClick={onHomeClick} aria-label="AnnWord — на главную" className="flex min-w-0 items-center gap-2 rounded-xl transition hover:opacity-80 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 sm:gap-2.5"><img src="/assets/branding/annword-logo-mark.svg" alt="" aria-hidden="true" className="h-10 w-10 shrink-0 object-contain sm:h-11 sm:w-11" draggable={false}/><span className="truncate text-lg font-black leading-none text-[#121821] sm:text-xl">AnnWord</span></button><span className="hidden rounded-full bg-indigo-50 px-3 py-1 text-xs font-black text-indigo-600 sm:inline-flex">{modeLabel}</span></div>
    {isAuthenticated && <nav className="hidden items-center gap-1 lg:flex"><button type="button" onClick={onHomeClick} className={navButton}>Главная</button>{isPractice && onDictionaryStudioClick && <button type="button" onClick={onDictionaryStudioClick} className={navButton}>Словари</button>}{isPractice && onProfileClick && <button type="button" onClick={onProfileClick} className={navButton}>Статистика</button>}{isParent && onShopClick && <button type="button" onClick={onShopClick} className={navButton}>Магазин</button>}{(isParent || isTeacher) && onAdultRoomClick && <button type="button" onClick={onAdultRoomClick} className={navButton}>{cabinetLabel}</button>}{isTeacher && onDictionaryStudioClick && <button type="button" onClick={onDictionaryStudioClick} className={navButton}>Словари</button>}</nav>}
    <div className="flex shrink-0 items-center gap-1.5 sm:gap-2">{showKidsEconomy && <button type="button" onClick={onShopClick} aria-label={`Монеты: ${userProfile.coins}. Открыть магазин`} className="flex items-center gap-1 rounded-xl border border-yellow-100 bg-yellow-50 px-2.5 py-2 text-sm font-black text-yellow-700 transition hover:bg-yellow-100 sm:px-3"><span>{userProfile.coins}</span><CoinIcon className="text-base" /></button>}{isAuthenticated ? <details ref={accountMenuRef} className="group relative"><summary className="flex max-w-[122px] cursor-pointer list-none items-center gap-1 rounded-xl bg-indigo-50 px-3 py-2 text-sm font-bold text-indigo-700 transition hover:bg-indigo-100 sm:max-w-[180px] [&::-webkit-details-marker]:hidden"><span className="truncate" title={userProfile.username}>{userProfile.username}</span><span aria-hidden="true" className="text-xs text-indigo-400">▾</span></summary><div className="absolute right-0 top-[calc(100%+0.45rem)] z-50 w-60 rounded-2xl border border-indigo-100 bg-white p-1.5 shadow-xl"><button type="button" onClick={() => go(onHomeClick)} className="w-full rounded-xl px-3 py-2.5 text-left text-sm font-bold text-indigo-800 transition hover:bg-indigo-50">Главная · {modeLabel}</button>{onProfileClick && <button type="button" onClick={() => go(onProfileClick)} className="w-full rounded-xl px-3 py-2.5 text-left text-sm font-bold text-indigo-800 transition hover:bg-indigo-50">{profileLabel}</button>}{showKidsEconomy && onShopClick && <button type="button" onClick={() => go(onShopClick)} className="w-full rounded-xl px-3 py-2.5 text-left text-sm font-bold text-indigo-800 transition hover:bg-indigo-50">Магазин</button>}{hasDictionaryStudio && onDictionaryStudioClick && <button type="button" onClick={() => go(onDictionaryStudioClick)} className="w-full rounded-xl px-3 py-2.5 text-left text-sm font-bold text-purple-700 transition hover:bg-purple-50">Словари</button>}{(isParent || isTeacher || isAdmin) && onAdultRoomClick && <button type="button" onClick={() => go(onAdultRoomClick)} className="w-full rounded-xl px-3 py-2.5 text-left text-sm font-bold text-purple-700 transition hover:bg-purple-50">{cabinetLabel}</button>}{isAdmin && onAdminClick && <button type="button" onClick={() => go(onAdminClick)} className="w-full rounded-xl px-3 py-2.5 text-left text-sm font-bold text-purple-700 transition hover:bg-purple-50">Администрирование</button>}<div className="my-1 h-px bg-indigo-50"/><button type="button" onClick={() => go(onLogoutClick)} className="w-full rounded-xl px-3 py-2.5 text-left text-sm font-bold text-gray-600 transition hover:bg-gray-50">Выйти</button></div></details> : <button type="button" onClick={onLoginClick} className="rounded-xl bg-indigo-600 px-3 py-2 text-sm font-black text-white transition hover:bg-indigo-700 sm:px-4">Войти</button>}</div>
  </header>;
};
