import React from 'react';
import { DictionarySource, DifficultyLevel, GameSettings, UserProfile } from '../../types';
import { getKidsDictionaryCatalog } from '../../services/kidsDictionaryCatalog';
import { isKidsMode } from '../../services/modeFlags';
import { getPremiumDictionaryCatalog, hasPremiumDictionaryAccess } from '../../services/premiumDictionaryCatalog';
import { ScreenContainer } from '../layout/ScreenContainer';

interface DictionarySettingsScreenProps { settings: GameSettings; userProfile: UserProfile; customDictionaryWords: string[]; isAuthenticated: boolean; onSettingsChange: (settings: GameSettings) => void; onOpenDictionaryStudio: () => void; onOpenPremium: () => void; onBack: () => void; }

const DIFFICULTIES: Array<{ value: DifficultyLevel; short: string }> = [{ value: 'ALL', short: 'Все' }, { value: 'A1', short: 'A1' }, { value: 'A2', short: 'A2' }, { value: 'B1', short: 'B1' }, { value: 'B2', short: 'B2' }, { value: 'C1', short: 'C1' }, { value: 'C2', short: 'C2' }];

export const DictionarySettingsScreen: React.FC<DictionarySettingsScreenProps> = ({ settings, userProfile, customDictionaryWords, isAuthenticated, onSettingsChange, onOpenDictionaryStudio, onOpenPremium, onBack }) => {
  const parentMode = isKidsMode(userProfile, isAuthenticated);
  const hasPremium = hasPremiumDictionaryAccess(userProfile);
  const source = settings.dictionarySource;
  const isBuiltin = source === 'builtin' && !settings.useCustomDictionary;
  const isCustom = source === 'custom' || settings.useCustomDictionary;
  const isPremium = source === 'premium';
  const premiumCatalog = parentMode ? getKidsDictionaryCatalog() : getPremiumDictionaryCatalog();
  const chooseSource = (nextSource: DictionarySource) => {
    if ((nextSource === 'custom' || nextSource === 'premium') && (!isAuthenticated || !hasPremium)) return onOpenPremium();
    onSettingsChange({ ...settings, dictionarySource: nextSource, useCustomDictionary: nextSource === 'custom' });
  };
  const cardClass = (active: boolean, tone: 'indigo' | 'purple' | 'amber') => {
    const activeTone = tone === 'purple' ? 'border-purple-300 bg-purple-50' : tone === 'amber' ? 'border-amber-300 bg-amber-50' : 'border-indigo-300 bg-indigo-50';
    return `rounded-[1.75rem] border-2 p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md ${active ? activeTone : 'border-indigo-50 bg-white hover:border-indigo-100'}`;
  };
  return <ScreenContainer className="max-w-5xl pb-20 pt-4">
    <header className="mb-5 flex items-center justify-between gap-3"><button type="button" onClick={onBack} aria-label="Назад" className="flex h-11 w-11 items-center justify-center rounded-2xl border-2 border-indigo-100 bg-white text-2xl font-black text-indigo-700">←</button><div className="text-center"><div className="text-xs font-black uppercase tracking-widest text-indigo-400">Слова для игр</div><h1 className="text-2xl font-black text-indigo-950 sm:text-3xl">Выбор словаря</h1></div><div className="h-11 w-11" /></header>
    <section className="rounded-[2rem] border-2 border-indigo-50 bg-white p-5 shadow-sm sm:p-6">
      <div className="mb-5 rounded-3xl bg-indigo-50 p-4"><h2 className="text-xl font-black text-indigo-950">Выберите слова под задачу</h2><p className="mt-2 text-sm font-bold leading-relaxed text-indigo-700">В бесплатном режиме доступен базовый набор. Premium открывает тематические наборы и тренировку по словам из вашего списка.</p></div>
      <div className="grid gap-4 md:grid-cols-3">
        <button type="button" onClick={() => chooseSource('builtin')} aria-pressed={isBuiltin} className={cardClass(isBuiltin, 'indigo')}><span className="text-3xl" aria-hidden="true">{parentMode ? '🌈' : '📚'}</span><h3 className="mt-4 text-2xl font-black text-indigo-950">{parentMode ? 'Детский словарь' : 'General English'}</h3><p className="mt-2 text-sm font-bold text-gray-500">{parentMode ? 'Бесплатные слова для детских игр.' : 'Встроенный словарь по уровням сложности.'}</p></button>
        <div className={cardClass(isCustom && hasPremium, 'purple')}><div className="flex items-start justify-between gap-3"><span className="text-3xl" aria-hidden="true">🧩</span><span className="rounded-full bg-purple-50 px-2 py-1 text-[10px] font-black uppercase tracking-widest text-purple-700">{hasPremium ? 'открыто' : 'Premium'}</span></div><h3 className="mt-4 text-2xl font-black text-indigo-950">Слова из вашего списка</h3><p className="mt-2 text-sm font-bold text-gray-500">{customDictionaryWords.length ? 'Ваш список готов для использования в играх.' : parentMode ? 'Добавьте слова из школы, курса или учебника.' : 'Добавьте слова из работы, экзамена, курса или своей темы.'}</p><div className="mt-4 grid gap-2 sm:grid-cols-2"><button type="button" onClick={() => chooseSource('custom')} className="rounded-xl border-2 border-purple-100 bg-white px-4 py-2.5 text-sm font-black text-purple-700 transition hover:bg-purple-50">Выбрать</button><button type="button" onClick={hasPremium ? onOpenDictionaryStudio : onOpenPremium} className="rounded-xl bg-purple-600 px-4 py-2.5 text-sm font-black text-white transition hover:bg-purple-700">Добавить слова</button></div></div>
        <button type="button" onClick={() => chooseSource('premium')} aria-pressed={isPremium && hasPremium} className={cardClass(isPremium && hasPremium, 'amber')}><span className="text-3xl" aria-hidden="true">✨</span><h3 className="mt-4 text-2xl font-black text-indigo-950">{parentMode ? 'Детские темы Premium' : 'Тематические словари'}</h3><p className="mt-2 text-sm font-bold text-gray-500">{parentMode ? 'Слова по классам и знакомым темам.' : 'Medical, IELTS, Business, IT и другие наборы.'}</p><span className="mt-4 inline-flex rounded-full bg-amber-50 px-3 py-1 text-xs font-black uppercase tracking-widest text-amber-700">{hasPremium ? 'доступ есть' : 'Premium'}</span></button>
      </div>
      {!hasPremium && <button type="button" onClick={onOpenPremium} className="mt-5 flex w-full flex-col gap-2 rounded-3xl border-2 border-amber-100 bg-amber-50 px-4 py-3 text-left transition hover:bg-amber-100/70 sm:flex-row sm:items-center sm:justify-between"><span><span className="block text-sm font-black text-amber-900">🔒 Темы и слова из вашего списка доступны в Premium</span><span className="mt-1 block text-xs font-bold text-amber-800/80">Откройте словари под задачу и играйте по словам, которые действительно нужно повторить.</span></span><span className="shrink-0 rounded-2xl bg-indigo-600 px-4 py-2 text-xs font-black text-white">Открыть</span></button>}
      {(isBuiltin || (isPremium && hasPremium)) && <section className="mt-6" aria-labelledby="dictionary-difficulty-title"><h2 id="dictionary-difficulty-title" className="mb-2 text-xs font-black uppercase tracking-widest text-indigo-400">{isPremium ? 'Уровень Premium-словаря' : parentMode ? 'Сложность детского словаря' : 'Сложность General English'}</h2><div className="grid grid-cols-4 gap-2 sm:grid-cols-7" role="group" aria-label="Сложность словаря">{DIFFICULTIES.map(level => <button type="button" key={level.value} aria-pressed={settings.difficulty === level.value} onClick={() => onSettingsChange({ ...settings, difficulty: level.value })} className={`rounded-2xl py-2.5 text-sm font-black ${settings.difficulty === level.value ? 'bg-indigo-600 text-white' : 'border-2 border-indigo-100 text-indigo-700'}`}>{level.short}</button>)}</div></section>}
      {isPremium && hasPremium && <section className="mt-6 rounded-2xl border-2 border-dashed border-amber-100 bg-amber-50/60 p-4"><h2 className="mb-3 text-xs font-black uppercase tracking-widest text-amber-500">{parentMode ? 'Выберите детскую тему' : 'Выберите Premium-тему'}</h2><div className="grid grid-cols-2 gap-2 sm:grid-cols-5" role="group" aria-label="Выбор Premium-словаря">{premiumCatalog.map(item => <button type="button" key={item.id} onClick={() => onSettingsChange({ ...settings, dictionarySource: 'premium', useCustomDictionary: false, activePremiumDictionaryId: item.id })} className={`rounded-2xl border-2 bg-white/70 p-3 text-left transition hover:bg-white ${settings.activePremiumDictionaryId === item.id ? 'border-amber-300' : 'border-white'}`}><div className="text-xl" aria-hidden="true">{item.icon}</div><div className="truncate text-xs font-black text-indigo-950">{item.shortTitle}</div></button>)}</div></section>}
      <button type="button" onClick={onBack} className="mt-6 w-full rounded-2xl bg-indigo-600 px-6 py-4 font-black text-white transition hover:bg-indigo-700">Готово</button>
    </section>
  </ScreenContainer>;
};