import React from 'react';
import { DailyQuestCompletionReward, DailyQuestState, UserProfile } from '../../types';
import { getCharacterProgressPercent, getCharacterStageLabel, getNextLevelThreshold, normalizeMoodScore } from '../../services/gamificationRules';
import { getMoodDisplay } from '../../services/moodDisplay';
import { getPetEmoji } from '../../services/petEngine';
import { getPuppyCharacterAssetUrl } from '../../services/petAssets';
import { CoinIcon } from '../CoinIcon';
import { DailyQuestCard, DailyQuestRewardModal } from '../DailyQuestCard';
import { ScreenContainer } from '../layout/ScreenContainer';

type Props = { userProfile: UserProfile; dailyQuest?: DailyQuestState | null; dailyQuestReward?: DailyQuestCompletionReward | null; onCloseDailyQuestReward?: () => void; onStartDailyQuest?: (quest: DailyQuestState) => void; hasActiveClassicGame?: boolean; hasActiveAnagramGame?: boolean; onStartClassic: () => void; onStartAnagrams: () => void; onStartTranslation: () => void; onStartSprint: () => void; onStartHangman: () => void; onStartMemory: () => void; onStartLetterSquare: () => void; onOpenShop: () => void; onOpenProfile?: () => void; onOpenPetRoom?: () => void; onOpenAdultRoom?: () => void; };
const games = [
  ['Классика', '/assets/games/game_classic.webp'],
  ['Анаграммы', '/assets/games/game_anagrams.webp'],
  ['1 из 2', '/assets/games/game_one_of_two.webp'],
  ['Спринт', '/assets/games/game_sprint.webp'],
  ['Виселица', '/assets/games/game_hangman.webp'],
  ['Память', '/assets/games/game_memory.webp'],
  ['Квадрат слов', '/assets/games/line_game.webp'],
] as const;
export const KidsHomeScreen: React.FC<Props> = ({ userProfile, dailyQuest, dailyQuestReward, onCloseDailyQuestReward, onStartDailyQuest, hasActiveClassicGame, hasActiveAnagramGame, onStartClassic, onStartAnagrams, onStartTranslation, onStartSprint, onStartHangman, onStartMemory, onStartLetterSquare, onOpenShop, onOpenProfile, onOpenPetRoom, onOpenAdultRoom }) => {
  const actions = [onStartClassic, onStartAnagrams, onStartTranslation, onStartSprint, onStartHangman, onStartMemory, onStartLetterSquare];
  const petUrl = getPuppyCharacterAssetUrl(userProfile.pet); const mood = getMoodDisplay(normalizeMoodScore(userProfile.pet)); const xpPercent = getCharacterProgressPercent(userProfile.pet); const nextLevelXp = getNextLevelThreshold(userProfile.pet.level || 1); const lastInventoryItem = userProfile.inventory.find(item => item.quantity > 0);
  return <ScreenContainer className="max-w-6xl pb-20 pt-4"><section className="grid gap-5 lg:grid-cols-[0.88fr_1.12fr]">
    <main className="order-1 lg:order-2"><div className="rounded-[2rem] border-2 border-indigo-50 bg-white p-4 shadow-sm sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="text-xs font-black uppercase tracking-widest text-indigo-400">AnnWord Kids</div><h1 className="mt-1 text-3xl font-black leading-tight text-indigo-950 sm:text-4xl">Во что сыграем?</h1><p className="mt-2 text-sm font-bold text-gray-500">Выбери игру, собери слова и порадуй питомца.</p></div><button type="button" onClick={onOpenProfile} className="rounded-2xl bg-indigo-50 px-4 py-2 text-sm font-black text-indigo-700">Профиль</button></div><div className="mt-4 grid grid-cols-3 gap-2"><div className="rounded-2xl bg-yellow-50 px-3 py-2 text-center"><CoinIcon className="text-xl" /><div className="text-lg font-black text-yellow-700">{userProfile.coins}</div><div className="text-[10px] font-black uppercase tracking-widest text-yellow-600/70">монет</div></div><div className="rounded-2xl bg-purple-50 px-3 py-2 text-center"><div className="text-lg font-black text-purple-700">{mood.label}</div><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-purple-100"><div className={`h-full ${mood.barClass}`} style={{ width: `${normalizeMoodScore(userProfile.pet)}%` }} /></div><div className="mt-1 text-[10px] font-black uppercase tracking-widest text-purple-600/70">настроение</div></div><div className="rounded-2xl bg-indigo-50 px-3 py-2 text-center"><div className="text-lg font-black text-indigo-700">ур. {userProfile.pet.level}</div><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-indigo-100"><div className="h-full rounded-full bg-indigo-600" style={{ width: `${xpPercent}%` }} /></div><div className="mt-1 text-[10px] font-black uppercase tracking-widest text-indigo-600/70">XP</div></div></div><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-3 sm:gap-3">{games.map(([label, src], index) => <button key={label} type="button" onClick={actions[index]} className="relative min-h-[7.5rem] rounded-3xl border-2 border-indigo-50 bg-white p-2 text-center shadow-sm transition hover:-translate-y-0.5 hover:border-indigo-100 hover:shadow-md"><img src={src} alt="" className="mx-auto h-14 w-14 object-contain sm:h-16 sm:w-16" draggable={false} /><div className="mt-2 truncate text-xs font-black text-indigo-950 sm:text-sm">{label}</div>{((index === 0 && hasActiveClassicGame) || (index === 1 && hasActiveAnagramGame)) && <div className="absolute right-1 top-1 rounded-full bg-green-100 px-2 py-1 text-[10px] font-black text-green-700">сохранено</div>}{(index === 2 || index === 6) && <div className="absolute right-1 top-1 rounded-full bg-pink-100 px-2 py-1 text-[10px] font-black text-pink-700">новая</div>}</button>)}</div></div>{dailyQuest && <DailyQuestCard quest={dailyQuest} onStart={onStartDailyQuest} onOpenPetRoom={onOpenPetRoom} onOpenShop={onOpenShop} />}</main>
    <aside className="order-2 rounded-[2rem] bg-gradient-to-br from-purple-700 to-indigo-700 p-5 text-white shadow-xl sm:p-7 lg:order-1"><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-black uppercase tracking-widest text-white/65">Питомец</div><h2 className="mt-1 text-3xl font-black">{userProfile.pet.name}</h2><div className="mt-1 text-sm font-bold text-white/70">{getCharacterStageLabel(userProfile.pet.stage)}</div></div><button type="button" onClick={onOpenPetRoom} className="rounded-2xl bg-white px-4 py-2 text-sm font-black text-indigo-700">Комната</button></div><button type="button" onClick={onOpenPetRoom} className="mx-auto mt-5 flex h-52 w-full max-w-[16rem] items-center justify-center overflow-hidden rounded-[2rem] bg-white/95 shadow-inner sm:h-56"><span className="sr-only">Комната питомца</span>{petUrl ? <img src={petUrl} alt="" className="h-64 w-64 scale-125 object-cover" draggable={false} /> : <span className="text-7xl">{getPetEmoji(userProfile.pet)}</span>}</button><div className="mt-5 grid grid-cols-2 gap-3"><button type="button" onClick={onOpenShop} aria-label={`Монеты: ${userProfile.coins}. Открыть магазин`} className="rounded-3xl bg-white/10 p-4 text-left"><CoinIcon className="text-3xl" /><div className="mt-3 text-3xl font-black">{userProfile.coins}</div><div className="text-xs font-black uppercase tracking-widest text-white/60">монет</div></button><div className="rounded-3xl bg-white/10 p-4"><div className={`text-xs font-black uppercase tracking-widest ${mood.textOnDarkClass}`}>{mood.label}</div><div className="mt-4 h-2 rounded-full bg-white/15"><div className={`h-2 rounded-full ${mood.barClass}`} style={{ width: `${normalizeMoodScore(userProfile.pet)}%` }} /></div><div className="mt-5 text-xs font-black uppercase tracking-widest text-white/60">XP</div><div className="mt-1 text-sm font-black text-white">{userProfile.pet.xp} / {nextLevelXp}</div><div className="mt-2 h-2 rounded-full bg-white/15"><div className="h-2 rounded-full bg-white" style={{ width: `${xpPercent}%` }} /></div></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-1"><button type="button" onClick={onOpenAdultRoom} className="rounded-3xl border border-white/15 bg-white/10 p-4 text-left transition hover:bg-white/15"><div className="text-xs font-black uppercase tracking-widest text-white/60">Для взрослого</div><div className="mt-1 text-sm font-black text-white">Кабинет родителя</div><div className="mt-1 text-xs font-bold text-white/65">Откроется через PIN.</div></button>{lastInventoryItem && <button type="button" onClick={onOpenPetRoom} className="rounded-3xl bg-white/10 p-4 text-left"><div className="text-xs font-black uppercase tracking-widest text-white/60">В предметах</div><div className="mt-1 text-sm font-black text-white">{lastInventoryItem.name} ×{lastInventoryItem.quantity}</div><div className="mt-1 text-xs font-bold text-white/65">Открыть комнату</div></button>}</div></aside>
  </section>{dailyQuestReward && onCloseDailyQuestReward && <DailyQuestRewardModal reward={dailyQuestReward} onClose={onCloseDailyQuestReward} onOpenPetRoom={onOpenPetRoom} onOpenShop={onOpenShop} />}</ScreenContainer>;
};