import React, { useState } from 'react';
import { DailyQuestCompletionReward, DailyQuestState, UserProfile } from '../../types';
import { CoinIcon } from '../CoinIcon';
import { DailyQuestCard, DailyQuestRewardModal } from '../DailyQuestCard';
import { ScreenContainer } from '../layout/ScreenContainer';

interface LandingScreenProps { userProfile: UserProfile; isAuthenticated: boolean; dailyQuest?: DailyQuestState | null; dailyQuestReward?: DailyQuestCompletionReward | null; onCloseDailyQuestReward?: () => void; onStartDailyQuest?: (quest: DailyQuestState) => void; hasActiveClassicGame?: boolean; hasActiveAnagramGame?: boolean; onStartClassic: () => void; onStartAnagrams: () => void; onStartSprint: () => void; onStartHangman: () => void; onStartMemory: () => void; onOpenShop: () => void; onOpenRules: () => void; onOpenLogin: () => void; onOpenRegister?: () => void; onOpenProfile?: () => void; onOpenPetRoom?: () => void; }
interface GameOption { title: string; description: string; iconSrc: string; onStart: () => void; hasSavedGame?: boolean; }
const PRACTICE_IMAGE = '/assets/onboarding/account-mode-practice-dog.webp';
const modeCards = [
  { title: 'Kids', imageSrc: '/assets/onboarding/account-mode-parent.webp', summary: 'Детская версия с питомцем, монетами, заданиями и кабинетом родителя.', details: ['Питомец, лакомства и мотивация', 'Родительский кабинет', 'Код ребёнка для преподавателя'] },
  { title: 'Practice', imageSrc: PRACTICE_IMAGE, summary: 'Взрослая ежедневная практика слов без детской экономики.', details: ['Ежедневные задания и streak', 'Тематические словари в Premium', 'Свои словари после регистрации'] },
  { title: 'Teacher', imageSrc: '/assets/onboarding/account-mode-teacher.webp', summary: 'Кабинет преподавателя для подключения учеников и назначения словарей.', details: ['Добавление ученика по коду', 'Просмотр прогресса', 'Словари преподавателя'] },
];
const gameOptions = (bindings: Pick<LandingScreenProps, 'hasActiveClassicGame' | 'hasActiveAnagramGame' | 'onStartClassic' | 'onStartAnagrams' | 'onStartSprint' | 'onStartHangman' | 'onStartMemory'>): GameOption[] => [
  { title: 'Классика', description: 'Угадайте слово за 6 попыток.', iconSrc: '/assets/games/game_classic.webp', onStart: bindings.onStartClassic, hasSavedGame: bindings.hasActiveClassicGame },
  { title: 'Анаграммы', description: 'Соберите слово из букв.', iconSrc: '/assets/games/game_anagrams.webp', onStart: bindings.onStartAnagrams, hasSavedGame: bindings.hasActiveAnagramGame },
  { title: 'Спринт', description: 'Быстрые ответы на время.', iconSrc: '/assets/games/game_sprint.webp', onStart: bindings.onStartSprint },
  { title: 'Виселица', description: 'Угадайте слово по буквам.', iconSrc: '/assets/games/game_hangman.webp', onStart: bindings.onStartHangman },
  { title: 'Память', description: 'Найдите пары слово–перевод.', iconSrc: '/assets/games/game_memory.webp', onStart: bindings.onStartMemory },
];
const GameIconButton: React.FC<GameOption> = ({ title, description, iconSrc, onStart, hasSavedGame }) => <button type="button" aria-label={title} onClick={onStart} className="group relative flex min-w-0 flex-col rounded-2xl border-2 border-indigo-50 bg-white p-3 text-left shadow-sm transition-all hover:-translate-y-1 hover:shadow-lg sm:rounded-3xl sm:p-4">{hasSavedGame && <span aria-label="Есть сохранённая игра" title="Есть сохранённая игра" className="absolute right-2 top-2 rounded-full bg-green-50 px-2 py-1 text-[10px] font-black text-green-700 shadow-sm">save</span>}<img src={iconSrc} alt="" aria-hidden="true" className="h-14 w-14 object-contain transition-transform group-hover:scale-110 sm:h-16 sm:w-16" draggable={false} /><span aria-hidden="true" className="mt-2 block text-sm font-black text-indigo-950 sm:text-base">{title}</span><span className="mt-1 text-xs font-bold leading-relaxed text-gray-500">{description}</span></button>;

export const LandingScreen: React.FC<LandingScreenProps> = ({ userProfile, isAuthenticated, dailyQuest, dailyQuestReward, onCloseDailyQuestReward, onStartDailyQuest, hasActiveClassicGame = false, hasActiveAnagramGame = false, onStartClassic, onStartAnagrams, onStartSprint, onStartHangman, onStartMemory, onOpenShop, onOpenLogin, onOpenRegister, onOpenProfile }) => {
  const [openMode, setOpenMode] = useState<string | null>('Practice');
  const isKids = userProfile.accountMode === 'parent' || userProfile.role === 'parent';
  const isPractice = isAuthenticated && !isKids && userProfile.role !== 'teacher' && userProfile.accountMode !== 'teacher';
  const games = gameOptions({ hasActiveClassicGame, hasActiveAnagramGame, onStartClassic, onStartAnagrams, onStartSprint, onStartHangman, onStartMemory });

  if (!isAuthenticated) return <ScreenContainer className="max-w-6xl pb-20 pt-6"><section className="rounded-[2rem] border-2 border-indigo-50 bg-white p-5 shadow-sm sm:p-8"><div className="grid gap-6 lg:grid-cols-[0.95fr_1.05fr] lg:items-center"><div><div className="text-xs font-black uppercase tracking-widest text-indigo-400">AnnWord</div><h1 className="mt-3 text-4xl font-black leading-tight text-indigo-950 sm:text-6xl">Английские слова в трёх форматах</h1><p className="mt-4 max-w-xl text-base font-bold leading-relaxed text-gray-600 sm:text-lg">Сначала можно попробовать игры без регистрации. Полный прогресс, свои словари и Premium-возможности открываются после создания аккаунта.</p><div className="mt-6 flex flex-col gap-3 sm:flex-row"><button type="button" onClick={onOpenRegister || onOpenLogin} className="rounded-2xl bg-indigo-600 px-6 py-4 font-black text-white transition hover:bg-indigo-700">Создать аккаунт</button><button type="button" onClick={onStartClassic} className="rounded-2xl border-2 border-indigo-100 bg-white px-6 py-4 font-black text-indigo-700 transition hover:bg-indigo-50">Попробовать игру</button></div></div><div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-1">{modeCards.map(card => <article key={card.title} className="rounded-3xl border-2 border-indigo-50 bg-indigo-50/40 p-4"><div className="flex items-center gap-3"><img src={card.imageSrc} alt="" aria-hidden="true" className="h-16 w-16 rounded-2xl bg-indigo-50 object-contain" draggable={false} /><div><h2 className="text-xl font-black text-indigo-950">{card.title}</h2><p className="mt-1 text-xs font-bold leading-relaxed text-gray-500">{card.summary}</p></div></div><button type="button" onClick={() => setOpenMode(openMode === card.title ? null : card.title)} className="mt-3 rounded-xl bg-white px-3 py-2 text-xs font-black text-indigo-600">Подробнее</button>{openMode === card.title && <div className="mt-3 space-y-2">{card.details.map(item => <div key={item} className="rounded-2xl bg-white px-3 py-2 text-xs font-bold text-gray-600">• {item}</div>)}</div>}</article>)}</div></div></section><section className="mt-6 rounded-[2rem] border-2 border-indigo-50 bg-white p-5 shadow-sm sm:p-6"><div className="mb-4"><div className="text-xs font-black uppercase tracking-widest text-indigo-400">Игры доступны сразу</div><h2 className="mt-1 text-2xl font-black text-indigo-950">Попробуйте механику до регистрации</h2></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-5">{games.map(game => <GameIconButton key={`${game.title}-${game.iconSrc}`} {...game} />)}</div></section></ScreenContainer>;

  if (isPractice) return <ScreenContainer className="max-w-6xl pb-20 pt-6"><section className="rounded-[2rem] bg-gradient-to-br from-indigo-700 to-sky-600 p-6 text-white shadow-xl sm:p-8"><div className="grid gap-5 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="text-xs font-black uppercase tracking-widest text-white/70">AnnWord Practice</div><h1 className="mt-3 text-4xl font-black leading-tight sm:text-5xl">Ежедневная практика английских слов</h1><p className="mt-4 max-w-2xl text-sm font-bold leading-relaxed text-white/75 sm:text-base">Выбирайте игру, уровень и словарь. Ежедневные задания продлевают streak и отражаются в стикерах.</p></div><button type="button" onClick={onOpenProfile} className="rounded-2xl bg-white px-5 py-3 font-black text-indigo-700">Статистика</button></div>{dailyQuest && <DailyQuestCard quest={dailyQuest} onStart={onStartDailyQuest} variant="practice" />}</section><section className="mt-6 rounded-[2rem] border-2 border-indigo-50 bg-white p-5 shadow-sm sm:p-6"><div className="grid grid-cols-2 gap-3 sm:grid-cols-5">{games.map(game => <GameIconButton key={`${game.title}-${game.iconSrc}`} {...game} />)}</div></section></ScreenContainer>;

  return <ScreenContainer className="pb-6 sm:pb-24"><section className="grid grid-cols-1 items-center gap-5 py-4 sm:py-8 lg:grid-cols-[1.1fr_0.9fr] lg:gap-8"><div><h1 className="mb-4 text-3xl font-black leading-tight text-indigo-950 sm:text-5xl">Во что сыграем сегодня?</h1><p className="mb-6 max-w-xl text-base leading-relaxed text-gray-600 sm:text-lg">Играйте и собирайте монеты. {userProfile.pet.name} будет расти вместе с вашими успехами.</p><div className="grid grid-cols-3 gap-2 sm:grid-cols-5 sm:gap-3">{games.map(game => <GameIconButton key={`${game.title}-${game.iconSrc}`} {...game} />)}</div>{isKids && dailyQuest && <DailyQuestCard quest={dailyQuest} onStart={onStartDailyQuest} />}</div><aside className="rounded-[2rem] bg-gradient-to-br from-indigo-600 to-purple-700 p-5 text-white shadow-2xl sm:p-6"><div className="mb-4 flex items-start justify-between gap-4"><div><div className="text-sm font-bold uppercase tracking-widest text-white/70">AnnWord Kids</div><div className="mt-1 text-2xl font-black">Игровой профиль</div></div><button type="button" onClick={onOpenProfile} className="rounded-2xl bg-white/15 px-4 py-2 text-sm font-black transition hover:bg-white/25">Профиль</button></div><div className="grid grid-cols-2 gap-3"><button type="button" onClick={onOpenShop} className="flex min-h-[8.25rem] flex-col justify-between rounded-2xl border border-white/10 bg-white/10 p-4 text-left transition hover:bg-white/15"><CoinIcon className="text-3xl" label="монеты" /><div><div className="text-2xl font-black">{userProfile.coins}</div><div className="text-xs font-bold uppercase tracking-widest text-white/65">монет</div></div></button><div className="flex min-h-[8.25rem] flex-col justify-between rounded-2xl border border-white/10 bg-white/10 p-4"><div className="text-xs font-black uppercase tracking-widest text-white/65">Уровень</div><div className="text-4xl font-black">{userProfile.pet.level}</div><div className="text-sm font-bold text-white/70">{userProfile.pet.name}</div></div></div></aside></section>{isKids && dailyQuestReward && onCloseDailyQuestReward && <DailyQuestRewardModal reward={dailyQuestReward} onClose={onCloseDailyQuestReward} />}</ScreenContainer>;
};
