import React from 'react';
import { UserProfile } from '../../types';
import { ScreenContainer } from '../layout/ScreenContainer';

interface ProfileScreenProps { userProfile: UserProfile; isAuthenticated: boolean; activeDictionaryName?: string; activeDictionaryWordCount?: number; onBackHome: () => void; onOpenShop: () => void; onOpenPetRoom: () => void; onLogin: () => void; }
const t = { back: '← На главную', login: 'Войти', guest: 'Гость', practice: 'AnnWord Practice', kids: 'AnnWord Kids', teacher: 'AnnWord Teacher', games: 'тренировок', wins: 'успешных', words: 'слов в активном словаре', coins: 'монет', level: 'уровень', collections: 'подборок', shop: 'Магазин', pet: 'Комната питомца' };
const Stat = ({ value, label }: { value: number | string; label: string }) => <div className="rounded-2xl border border-indigo-100 bg-white p-4"><div className="text-3xl font-black text-indigo-950">{value}</div><div className="mt-1 text-xs font-black uppercase tracking-widest text-indigo-400">{label}</div></div>;

export const ProfileScreen: React.FC<ProfileScreenProps> = ({ userProfile, isAuthenticated, activeDictionaryName, activeDictionaryWordCount, onBackHome, onOpenShop, onOpenPetRoom, onLogin }) => {
  const isKids = userProfile.role === 'parent' || userProfile.accountMode === 'parent';
  const isTeacher = userProfile.role === 'teacher' || userProfile.accountMode === 'teacher';
  const title = !isAuthenticated ? t.guest : isTeacher ? t.teacher : isKids ? t.kids : t.practice;
  const note = isTeacher ? 'Кабинет без игр: ученики, прогресс и словари.' : isKids ? 'Детский режим: питомец, монеты, родительский кабинет.' : 'Взрослый режим: слова, словари и статистика без детской экономики.';
  const dictionaryLabel = activeDictionaryName ? `${activeDictionaryName}` : 'Активный словарь';
  const dictionaryCount = activeDictionaryWordCount ?? userProfile.customDictionaryEn.length;
  return <ScreenContainer className="max-w-4xl pb-20 pt-6"><button type="button" onClick={onBackHome} className="mb-5 rounded-2xl border-2 border-indigo-100 bg-white px-4 py-2 text-sm font-black text-indigo-700">{t.back}</button><section className="rounded-[2rem] border-2 border-indigo-50 bg-indigo-50/50 p-5 sm:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-xs font-black uppercase tracking-widest text-indigo-400">{title}</div><h1 className="mt-1 text-3xl font-black text-indigo-950">{userProfile.username || title}</h1><p className="mt-2 text-sm font-bold text-gray-500">{note}</p>{!isTeacher && <p className="mt-2 text-xs font-black uppercase tracking-widest text-indigo-400">{dictionaryLabel}</p>}</div>{!isAuthenticated && <button type="button" onClick={onLogin} className="rounded-2xl bg-indigo-600 px-5 py-3 font-black text-white">{t.login}</button>}</div><div className="mt-6 grid gap-3 sm:grid-cols-3"><Stat value={userProfile.stats.gamesPlayed} label={t.games} /><Stat value={userProfile.stats.gamesWon} label={t.wins} /><Stat value={dictionaryCount} label={t.words} />{isKids && <><Stat value={userProfile.coins} label={t.coins} /><Stat value={userProfile.pet.level} label={t.level} /></>}{isTeacher && <Stat value={(userProfile.dictionaryCollections || []).length} label={t.collections} />}</div>{isKids && <div className="mt-5 flex flex-col gap-3 sm:flex-row"><button type="button" onClick={onOpenPetRoom} className="rounded-2xl bg-purple-600 px-5 py-3 font-black text-white">{t.pet}</button><button type="button" onClick={onOpenShop} className="rounded-2xl bg-yellow-400 px-5 py-3 font-black text-yellow-950">{t.shop}</button></div>}</section></ScreenContainer>;
};
