import { UserProfile, UserStats, PetState, ShopItem } from '../types';
import { supabase } from '../supabase';
import { mapProfileFromDB, normalizeDictionaryField, normalizePet, normalizeStats } from './profileMapper';
import { applyPurchaseLocally } from './economyEngine';
import { getShopItemById } from './shopCatalog';
import { runPetMoodClock } from './petMoodClock';
import { QueuedAnalyticsEvent } from './analyticsService';
import { GameLedgerEvent } from './gameEventLedgerService';
import { premiumDictionaryService } from './premiumDictionaryService';
import { isBackendApiConfigured } from './backendApiClient';
import { profileApiService } from './profileApiService';
import { consumePendingRegisteredProfile } from './authService';
const PROFILE_COLUMNS='id, username, role, account_mode, subscription_tier, premium_expires_at, feature_flags, dictionary_collections, weekly_report_email, child_display_name, child_share_code, child_slots_limit, custom_dictionary_en, stats, pet, coins, inventory';
const DEFAULT_PET:PetState={name:'Щенок',type:'Puppy',level:1,mood:'happy',xp:0,moodScore:60,stage:'stage_1',characterOnboarded:false,hunger:60,energy:60,equippedAccessories:[]};
const DEFAULT_STATS:UserStats={gamesPlayed:0,gamesWon:0,wordsGuessed:{},wordsToReview:{},wordPerformance:{},wordLearningHistory:{}};
const itemPayload=(item:ShopItem)=>({id:item.id,type:item.type,name:item.name,price:item.price,imageUrl:item.imageUrl||'',effect:item.effect||{},characterType:item.characterType||''});
const withTimeout=async(request:any,ms:number,label:string):Promise<any>=>{let t:ReturnType<typeof setTimeout>|undefined;const timeout=new Promise<never>((_,reject)=>{t=setTimeout(()=>reject(new Error(`${label} timeout`)),ms)});try{return await Promise.race([Promise.resolve(request),timeout])}finally{if(t)clearTimeout(t)}};
const hydrateCollections=async(profile:UserProfile):Promise<UserProfile>=>{try{const collections=await withTimeout(premiumDictionaryService.listCollections(),2200,'dictionary collections fetch');return collections.length?{...profile,dictionaryCollections:collections}:profile}catch(error){console.warn('Could not hydrate dictionary collections',error);return profile}};
const withAccess=(base:UserProfile, refreshed:UserProfile|null):UserProfile=>refreshed?{...refreshed,role:base.role,accountMode:base.accountMode,subscriptionTier:base.subscriptionTier,premiumExpiresAt:base.premiumExpiresAt,childDisplayName:base.childDisplayName,childShareCode:base.childShareCode,childSlotsLimit:base.childSlotsLimit,featureFlags:base.featureFlags,dictionaryCollections:base.dictionaryCollections,weeklyReportEmail:base.weeklyReportEmail,assignedWords:base.assignedWords}:base;
const normalizeEmail=(email:string):string|null=>{const value=email.trim().toLowerCase();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)?value:null};
export const userService={
 getOrCreateProfile:async(userId:string,defaultUsername='Пользователь',email?:string):Promise<UserProfile>=>{if(isBackendApiConfigured){const registeredProfile=consumePendingRegisteredProfile(userId);return registeredProfile||profileApiService.getCurrentProfile()}const admins=(import.meta.env.VITE_ADMIN_EMAILS||'').split(',').map((e:string)=>e.trim()).filter(Boolean),role:'admin'|'user'=admins.includes(email??'')?'admin':'user';const{data:found,error}=await withTimeout(supabase.from('profiles').select(PROFILE_COLUMNS).eq('id',userId).maybeSingle(),3500,'profile fetch');if(error&&error.code!=='PGRST116')throw error;if(found){const base=await hydrateCollections(mapProfileFromDB(found));return withAccess(base,await runPetMoodClock('decay'))}const profile={id:userId,username:defaultUsername,role,account_mode:role==='admin'?'player':null,custom_dictionary_en:[],stats:DEFAULT_STATS,pet:{...DEFAULT_PET},coins:0,inventory:[]};const{data,error:insertError}=await withTimeout(supabase.from('profiles').insert([profile]).select(PROFILE_COLUMNS).single(),4500,'profile insert');if(insertError)throw insertError;if(!data)throw new Error('Сервер не вернул созданный профиль.');const base=await hydrateCollections(mapProfileFromDB(data));return withAccess(base,await runPetMoodClock('touch'))},
 applyGameResult:async(userId:string,stats:UserStats,pet:PetState,coinsDelta:number,events:QueuedAnalyticsEvent[]=[],gameEvents:GameLedgerEvent[]=[]):Promise<UserProfile>=>{if(isBackendApiConfigured)return profileApiService.applyGameResult(stats,pet,coinsDelta);const{data,error}=await withTimeout(supabase.rpc('apply_game_result',{p_user_id:userId,p_stats:normalizeStats(stats),p_pet:normalizePet(pet),p_coins_delta:Math.round(coinsDelta||0),p_analytics_events:events,p_game_events:gameEvents}),5000,'apply game result');if(error)throw error;if(!data)throw new Error('Сервер не вернул обновлённый профиль.');const base=mapProfileFromDB(data);return withAccess(base,await runPetMoodClock('touch'))},
 syncProfileState:async(userId:string,profile:Pick<UserProfile,'inventory'|'pet'|'coins'>,events:QueuedAnalyticsEvent[]=[]):Promise<UserProfile>=>{if(isBackendApiConfigured)return profileApiService.syncProfileState(profile);let result:any;try{result=await withTimeout(supabase.rpc('sync_profile_state',{p_user_id:userId,p_inventory:profile.inventory,p_pet:normalizePet(profile.pet),p_coins:Math.max(0,Math.round(profile.coins||0)),p_analytics_events:events}),2200,'purchase save')}catch{throw new Error('Не удалось быстро сохранить покупку. Попробуйте ещё раз.')}const{data,error}=result;if(error)throw error;if(!data)throw new Error('Сервер не вернул обновлённый профиль.');return mapProfileFromDB(data)},
 updateCoins:async(userId:string,amount:number):Promise<UserProfile|void>=>{if(isBackendApiConfigured)return profileApiService.incrementCoins(amount);try{const{error}=await supabase.rpc('increment_coins',{user_id:userId,amount});if(!error)return;const{data,error:readError}=await supabase.from('profiles').select('coins').eq('id',userId).single();if(readError)throw readError;const{error:writeError}=await supabase.from('profiles').update({coins:Math.max(0,(data?.coins??0)+amount)}).eq('id',userId);if(writeError)throw writeError}catch(error){console.error('Error in updateCoins:',error)}},
 buyCurrentUserItem:async(item:ShopItem):Promise<UserProfile|null>=>{const{data,error}=await supabase.auth.getUser();return error||!data.user?null:userService.buyItem(data.user.id,item)},
 buyItem:async(userId:string,item:ShopItem,optimistic?:UserProfile,events:QueuedAnalyticsEvent[]=[]):Promise<UserProfile>=>{if(item.type==='mystery'||item.id==='mystery_box')throw new Error('Секретная коробка доступна только за ежедневное задание.');if(isBackendApiConfigured)return profileApiService.purchaseItem(item.id);if(optimistic)return userService.syncProfileState(userId,optimistic,events);try{const{data,error}=await withTimeout(supabase.rpc('purchase_shop_item',{p_user_id:userId,p_item:itemPayload(item)}),2200,'purchase save');if(!error&&data)return mapProfileFromDB(data)}catch{throw new Error('Не удалось быстро сохранить покупку. Попробуйте ещё раз.')}const{data,error}=await withTimeout(supabase.from('profiles').select(PROFILE_COLUMNS).eq('id',userId).single(),2200,'purchase profile fetch');if(error)throw error;const purchase=applyPurchaseLocally(mapProfileFromDB(data),item);if(!purchase.ok||!purchase.profile)throw new Error(purchase.reason||'Покупка не удалась');return userService.syncProfileState(userId,purchase.profile,events)},
 useItem:async(userId:string,itemId:string,optimistic?:UserProfile,events:QueuedAnalyticsEvent[]=[]):Promise<UserProfile>=>{if(isBackendApiConfigured)return profileApiService.useItem(itemId);let profile:UserProfile;if(optimistic)profile=await userService.syncProfileState(userId,optimistic,events);else{const{data,error}=await withTimeout(supabase.from('profiles').select(PROFILE_COLUMNS).eq('id',userId).single(),8000,'use item profile fetch');if(error)throw error;profile=mapProfileFromDB(data)}return getShopItemById(itemId)?.type==='food'?withAccess(profile,await runPetMoodClock('touch')):profile},
 updateUserStats:async(userId:string,stats:UserStats):Promise<UserProfile|void>=>{if(isBackendApiConfigured)return profileApiService.updateStats(stats);const{error}=await supabase.from('profiles').update({stats:normalizeStats(stats)}).eq('id',userId);if(error)throw error},
 updateUserDictionary:async(userId:string,dictionary:string[]):Promise<UserProfile>=>{if(isBackendApiConfigured)return profileApiService.updateUserDictionary(dictionary);const{data,error}=await supabase.from('profiles').update({custom_dictionary_en:normalizeDictionaryField(dictionary),updated_at:new Date().toISOString()}).eq('id',userId).select(PROFILE_COLUMNS).single();if(error)throw error;if(!data)throw new Error('Сервер не вернул обновлённый профиль.');return mapProfileFromDB(data)},
 updateWeeklyReportEmail:async(email:string):Promise<UserProfile>=>{if(isBackendApiConfigured)return profileApiService.updateWeeklyReportEmail(email);const normalized=normalizeEmail(email);if(!normalized)throw new Error('Введите корректный email для отчёта.');const{data:userData,error:userError}=await supabase.auth.getUser();if(userError||!userData.user)throw new Error('Для настройки отчёта нужно войти.');const{data,error}=await supabase.from('profiles').update({weekly_report_email:normalized,updated_at:new Date().toISOString()}).eq('id',userData.user.id).select(PROFILE_COLUMNS).single();if(error)throw error;if(!data)throw new Error('Сервер не вернул обновлённый профиль.');return mapProfileFromDB(data)},
 updateUserPet:async(userId:string,pet:PetState):Promise<UserProfile|void>=>{if(isBackendApiConfigured)return profileApiService.updatePet(pet);const{error}=await supabase.from('profiles').update({pet:normalizePet(pet)}).eq('id',userId);if(error)throw error},
 getAllUsersStats:async():Promise<UserProfile[]>=>{const{data,error}=await supabase.from('profiles').select(PROFILE_COLUMNS);if(error)throw error;return data.map(mapProfileFromDB)}
};
