import { UserProfile, UserStats, PetState, ShopItem } from '../types';
import { supabase } from '../supabase';
import { mapProfileFromDB, normalizeDictionaryField, normalizePet, normalizeStats } from './profileMapper';
import { applyPurchaseLocally } from './economyEngine';
import { QueuedAnalyticsEvent } from './analyticsService';
const PROFILE_COLUMNS='id, username, role, custom_dictionary_en, stats, pet, coins, inventory';
const DEFAULT_PET:PetState={name:'Щенок',type:'Puppy',level:1,mood:'happy',xp:0,moodScore:60,stage:'stage_1',characterOnboarded:false,hunger:60,energy:60,equippedAccessories:[]};
const DEFAULT_STATS:UserStats={gamesPlayed:0,gamesWon:0,wordsGuessed:{}};
const itemPayload=(item:ShopItem)=>({id:item.id,type:item.type,name:item.name,price:item.price,imageUrl:item.imageUrl||'',effect:item.effect||{},characterType:item.characterType||''});
const withTimeout=async(request:any,ms:number,label:string):Promise<any>=>{let t:ReturnType<typeof setTimeout>|undefined;const timeout=new Promise<never>((_,reject)=>{t=setTimeout(()=>reject(new Error(`${label} timeout`)),ms)});try{return await Promise.race([Promise.resolve(request),timeout])}finally{if(t)clearTimeout(t)}};
export const userService={
 getOrCreateProfile:async(userId:string,defaultUsername='Пользователь',email?:string):Promise<UserProfile>=>{const admins=(import.meta.env.VITE_ADMIN_EMAILS||'').split(',').map((e:string)=>e.trim()).filter(Boolean),role:'admin'|'user'=admins.includes(email??'')?'admin':'user';const{data:found,error}=await withTimeout(supabase.from('profiles').select(PROFILE_COLUMNS).eq('id',userId).maybeSingle(),3500,'profile fetch');if(error&&error.code!=='PGRST116')throw error;if(found)return mapProfileFromDB(found);const profile={id:userId,username:defaultUsername,role,custom_dictionary_en:[],stats:DEFAULT_STATS,pet:{...DEFAULT_PET},coins:0,inventory:[]};const{data,error:insertError}=await withTimeout(supabase.from('profiles').insert([profile]).select(PROFILE_COLUMNS).single(),4500,'profile insert');if(insertError)throw insertError;if(!data)throw new Error('Сервер не вернул созданный профиль.');return mapProfileFromDB(data)},
 applyGameResult:async(userId:string,stats:UserStats,pet:PetState,coinsDelta:number,events:QueuedAnalyticsEvent[]=[]):Promise<UserProfile>=>{const{data,error}=await withTimeout(supabase.rpc('apply_game_result',{p_user_id:userId,p_stats:normalizeStats(stats),p_pet:normalizePet(pet),p_coins_delta:Math.round(coinsDelta||0),p_analytics_events:events}),5000,'apply game result');if(error)throw error;if(!data)throw new Error('Сервер не вернул обновлённый профиль.');return mapProfileFromDB(data)},
 syncProfileState:async(userId:string,profile:Pick<UserProfile,'inventory'|'pet'|'coins'>,events:QueuedAnalyticsEvent[]=[]):Promise<UserProfile>=>{const{data,error}=await withTimeout(supabase.rpc('sync_profile_state',{p_user_id:userId,p_inventory:profile.inventory,p_pet:normalizePet(profile.pet),p_coins:Math.max(0,Math.round(profile.coins||0)),p_analytics_events:events}),5000,'sync profile state');if(error)throw error;if(!data)throw new Error('Сервер не вернул обновлённый профиль.');return mapProfileFromDB(data)},
 updateCoins:async(userId:string,amount:number):Promise<void>=>{try{const{error}=await supabase.rpc('increment_coins',{user_id:userId,amount});if(!error)return;const{data,error:readError}=await supabase.from('profiles').select('coins').eq('id',userId).single();if(readError)throw readError;const{error:writeError}=await supabase.from('profiles').update({coins:Math.max(0,(data?.coins??0)+amount)}).eq('id',userId);if(writeError)throw writeError}catch(error){console.error('Error in updateCoins:',error)}},
 buyCurrentUserItem:async(item:ShopItem):Promise<UserProfile|null>=>{const{data,error}=await supabase.auth.getUser();return error||!data.user?null:userService.buyItem(data.user.id,item)},
 buyItem:async(userId:string,item:ShopItem,optimistic?:UserProfile,events:QueuedAnalyticsEvent[]=[]):Promise<UserProfile>=>{if(optimistic)return userService.syncProfileState(userId,optimistic,events);if(item.type!=='mystery'){try{const{data,error}=await supabase.rpc('purchase_shop_item',{p_user_id:userId,p_item:itemPayload(item)});if(!error&&data)return mapProfileFromDB(data)}catch{}}const{data,error}=await withTimeout(supabase.from('profiles').select(PROFILE_COLUMNS).eq('id',userId).single(),3500,'purchase profile fetch');if(error)throw error;const purchase=applyPurchaseLocally(mapProfileFromDB(data),item);if(!purchase.ok||!purchase.profile)throw new Error(purchase.reason||'Покупка не удалась');return userService.syncProfileState(userId,purchase.profile,events)},
 useItem:async(userId:string,_itemId:string,optimistic?:UserProfile,events:QueuedAnalyticsEvent[]=[]):Promise<UserProfile>=>{if(optimistic)return userService.syncProfileState(userId,optimistic,events);const{data,error}=await withTimeout(supabase.from('profiles').select(PROFILE_COLUMNS).eq('id',userId).single(),8000,'use item profile fetch');if(error)throw error;return mapProfileFromDB(data)},
 updateUserStats:async(userId:string,stats:UserStats):Promise<void>=>{const{error}=await supabase.from('profiles').update({stats:normalizeStats(stats)}).eq('id',userId);if(error)throw error},
 updateUserDictionary:async(userId:string,dictionary:string[]):Promise<UserProfile>=>{const{data,error}=await supabase.from('profiles').update({custom_dictionary_en:normalizeDictionaryField(dictionary),updated_at:new Date().toISOString()}).eq('id',userId).select(PROFILE_COLUMNS).single();if(error)throw error;if(!data)throw new Error('Сервер не вернул обновлённый профиль.');return mapProfileFromDB(data)},
 updateUserPet:async(userId:string,pet:PetState):Promise<void>=>{const{error}=await supabase.from('profiles').update({pet:normalizePet(pet)}).eq('id',userId);if(error)throw error},
 getAllUsersStats:async():Promise<UserProfile[]>=>{const{data,error}=await supabase.from('profiles').select(PROFILE_COLUMNS);if(error)throw error;return data.map(mapProfileFromDB)}
};