import React from 'react';
import { AppRouter } from './AppRouter';
import { LandingScreen } from './screens/LandingScreen';
import { PracticeHomeScreen } from './screens/PracticeHomeScreen';
import { PremiumScreen } from './screens/PremiumScreen';
import { KidsHomeScreen } from './screens/KidsHomeScreen';
import { TeacherDashboardScreen } from './screens/TeacherDashboardScreen';
import { SetupScreen } from './screens/SetupScreen';
import { ClassicGameScreen } from './screens/ClassicGameScreen';
import { ProfileScreen } from './screens/ProfileScreen';
import { AccountModeSetupScreen } from './screens/AccountModeSetupScreen';
import { CharacterOnboardingScreen } from './screens/CharacterOnboardingScreen';
import { FamilySetupScreen } from './screens/FamilySetupScreen';
import { AdminControlCenterScreen } from './screens/AdminControlCenterScreen';
import { AdultRoomScreen } from './screens/AdultRoomScreen';
import { DictionaryStudioScreen } from './screens/DictionaryStudioScreen';
import { AnagramsScreen, HangmanScreen, MemoryScreen, SprintScreen } from './screens/ModeScreens';
import { hasSavedAnagramSession } from './AnagramGame';
import { Shop } from './Shop';
import { PetRoom } from './PetRoom';
import { AccountMode, DailyQuestCompletionReward, DailyQuestState, GameSettings, GameState, CharStatus, PetState, ShopItem, UserProfile, ViewState, WordLength } from '../types';
import { GameRewardInput } from '../services/gamificationRules';
import { WordPracticeResult } from '../services/gameSessionEngine';
import { PremiumDictionaryDraft } from '../services/premiumDictionaryService';
import { ChildSetupResult } from '../services/familyAccountService';
import { getPremiumDictionaryMeta } from '../services/premiumDictionaryCatalog';

export type PlayableModeRoute = 'game' | 'anagrams' | 'sprint' | 'memory' | 'hangman';
export interface ClassicGameScreenBindings { setupError: string | null; gameState: GameState; keyStatuses: Record<string, CharStatus>; shakeRowIndex: number | null; hasActiveGame?: boolean; resumeGame?: () => boolean; startNewGame: () => void; handleChar: (char: string) => void; handleDelete: () => void; handleEnter: () => void | Promise<void>; fetchHint: () => void | Promise<void>; }
export interface DictionaryUploadBindings { isUploadingDictionary: boolean; error: string | null; onFileUpload: (event: React.ChangeEvent<HTMLInputElement>) => void; }
export interface AppScreensProps { route: ViewState; userProfile: UserProfile; isAuthenticated: boolean; dailyQuest?: DailyQuestState | null; dailyQuestReward?: DailyQuestCompletionReward | null; onCloseDailyQuestReward?: () => void; settings: GameSettings; modeWords: string[]; activeDictionaryWordCount?: number; selectedPlayMode: PlayableModeRoute; classicGame: ClassicGameScreenBindings; dictionaryUpload: DictionaryUploadBindings; onRouteChange: (route: ViewState) => void; onSelectedPlayModeChange: (mode: PlayableModeRoute) => void; onSettingsChange: (settings: GameSettings | ((prev: GameSettings) => GameSettings)) => void; onOpenLogin: () => void; onOpenRegister: () => void; onOpenRules: () => void; onBuy: (item: ShopItem) => Promise<void>; onUseItem: (itemId: string) => Promise<void>; onUpdatePet: (pet: PetState) => Promise<void>; onSaveDictionary: (draft: PremiumDictionaryDraft) => Promise<void>; onSelectAccountMode: (mode: AccountMode) => Promise<void>; onCreateChild: (childName: string, pin: string) => Promise<ChildSetupResult>; onChildSetupComplete: (result: ChildSetupResult) => void; onGameReward: (input: GameRewardInput) => Promise<void>; onWordPractice?: (word: string, result: WordPracticeResult) => Promise<void>; onCharacterOnboardingComplete: (character: PetState) => Promise<void>; onGameStarted?: (mode: PlayableModeRoute) => void; onTestUnlockPremium?: () => void; onDictionaryPeek?: () => boolean | Promise<boolean>; }
const WORD_LENGTHS: WordLength[] = [4, 5, 6];
const randomWordLength = (): WordLength => WORD_LENGTHS[Math.floor(Math.random() * WORD_LENGTHS.length)];
export const AppScreens: React.FC<AppScreensProps> = ({ route, userProfile, isAuthenticated, dailyQuest, dailyQuestReward, onCloseDailyQuestReward, settings, modeWords, activeDictionaryWordCount, selectedPlayMode, classicGame, dictionaryUpload, onRouteChange, onSelectedPlayModeChange, onSettingsChange, onOpenLogin, onOpenRegister, onOpenRules, onBuy, onUseItem, onUpdatePet, onSaveDictionary, onSelectAccountMode, onCreateChild, onChildSetupComplete, onGameReward, onWordPractice, onCharacterOnboardingComplete, onGameStarted, onTestUnlockPremium, onDictionaryPeek }) => {
  const goHome = () => onRouteChange('landing');
  const isParentAccount = userProfile.role === 'parent' || userProfile.accountMode === 'parent';
  const isTeacher = userProfile.role === 'teacher' || userProfile.accountMode === 'teacher';
  const isPractice = isAuthenticated && !isParentAccount && !isTeacher;
  const openDictionaryFromGameArea = () => onRouteChange(isParentAccount ? 'adult_room' : 'dictionary_studio');
  const setupError = classicGame.setupError || dictionaryUpload.error;
  const hasActiveClassicGame = Boolean(classicGame.hasActiveGame);
  const hasActiveAnagramGame = isAuthenticated && hasSavedAnagramSession(userProfile.username);
  const premiumMeta = getPremiumDictionaryMeta(settings.activePremiumDictionaryId);
  const activeDictionaryName = settings.dictionarySource === 'custom' || settings.useCustomDictionary ? 'Мой словарь' : settings.dictionarySource === 'premium' ? premiumMeta.title : 'General English';
  const activeDictionaryIcon = settings.dictionarySource === 'custom' || settings.useCustomDictionary ? '📖' : settings.dictionarySource === 'premium' ? premiumMeta.icon : '📚';
  const dictionaryWordCount = activeDictionaryWordCount ?? modeWords.length;
  const openSetupFor = (mode: PlayableModeRoute) => { if (isTeacher) return; if (mode === 'game' && hasActiveClassicGame && classicGame.resumeGame?.()) return; if (mode === 'anagrams' && hasActiveAnagramGame) { onSelectedPlayModeChange(mode); onRouteChange('anagrams'); return; } onSelectedPlayModeChange(mode); onRouteChange('setup'); };
  const startSelectedMode = () => { onGameStarted?.(selectedPlayMode); if (selectedPlayMode === 'game') { classicGame.startNewGame(); return; } onRouteChange(selectedPlayMode); };
  const startDailyQuest = (quest: DailyQuestState) => { const mode: PlayableModeRoute = quest.kind === 'hangman_clean' ? 'hangman' : quest.kind === 'sprint_twelve' ? 'sprint' : quest.kind === 'memory_sixteen' ? 'memory' : 'game'; onSelectedPlayModeChange(mode); onSettingsChange(previous => ({ ...previous, wordLength: randomWordLength() })); onRouteChange('setup'); };
  const guestLanding = <LandingScreen userProfile={userProfile} isAuthenticated={isAuthenticated} dailyQuest={dailyQuest} dailyQuestReward={dailyQuestReward} onCloseDailyQuestReward={onCloseDailyQuestReward} onStartDailyQuest={startDailyQuest} hasActiveClassicGame={hasActiveClassicGame} hasActiveAnagramGame={hasActiveAnagramGame} onStartClassic={() => openSetupFor('game')} onStartAnagrams={() => openSetupFor('anagrams')} onStartSprint={() => openSetupFor('sprint')} onStartHangman={() => openSetupFor('hangman')} onStartMemory={() => openSetupFor('memory')} onOpenShop={() => isParentAccount ? onRouteChange('shop') : onRouteChange('landing')} onOpenRules={onOpenRules} onOpenLogin={onOpenLogin} onOpenRegister={onOpenRegister} onOpenProfile={() => onRouteChange('profile')} onOpenPetRoom={() => isParentAccount ? onRouteChange('pet_room') : onRouteChange('landing')} />;
  const practiceHome = <PracticeHomeScreen userProfile={userProfile} dailyQuest={dailyQuest} dailyQuestReward={dailyQuestReward} onCloseDailyQuestReward={onCloseDailyQuestReward} onStartDailyQuest={startDailyQuest} hasActiveClassicGame={hasActiveClassicGame} hasActiveAnagramGame={hasActiveAnagramGame} activeDictionaryName={activeDictionaryName} activeDictionaryWordCount={dictionaryWordCount} onStartClassic={() => openSetupFor('game')} onStartAnagrams={() => openSetupFor('anagrams')} onStartSprint={() => openSetupFor('sprint')} onStartHangman={() => openSetupFor('hangman')} onStartMemory={() => openSetupFor('memory')} onOpenProfile={() => onRouteChange('profile')} onOpenDictionaryStudio={() => onRouteChange('setup')} onOpenPremium={() => onRouteChange('premium')} />;
  const kidsHome = <KidsHomeScreen userProfile={userProfile} dailyQuest={dailyQuest} dailyQuestReward={dailyQuestReward} onCloseDailyQuestReward={onCloseDailyQuestReward} onStartDailyQuest={startDailyQuest} hasActiveClassicGame={hasActiveClassicGame} hasActiveAnagramGame={hasActiveAnagramGame} onStartClassic={() => openSetupFor('game')} onStartAnagrams={() => openSetupFor('anagrams')} onStartSprint={() => openSetupFor('sprint')} onStartHangman={() => openSetupFor('hangman')} onStartMemory={() => openSetupFor('memory')} onOpenShop={() => onRouteChange('shop')} onOpenProfile={() => onRouteChange('profile')} onOpenPetRoom={() => onRouteChange('pet_room')} />;
  const teacherHome = <TeacherDashboardScreen userProfile={userProfile} onOpenDictionaryStudio={() => onRouteChange('dictionary_studio')} onOpenAdultRoom={() => onRouteChange('adult_room')} onOpenProfile={() => onRouteChange('profile')} />;
  const homeScreen = isTeacher ? teacherHome : isParentAccount ? kidsHome : isPractice ? practiceHome : guestLanding;
  const screens: Partial<Record<ViewState, React.ReactNode>> = {
    admin: <AdminControlCenterScreen userProfile={userProfile} onBackHome={goHome} />, adult_room: <AdultRoomScreen userProfile={userProfile} onBackHome={goHome} onOpenDictionaryStudio={() => onRouteChange('dictionary_studio')} />, dictionary_studio: <DictionaryStudioScreen userProfile={userProfile} onBack={() => onRouteChange(isParentAccount || isTeacher ? 'adult_room' : 'landing')} onSaveDictionary={onSaveDictionary} />, premium: <PremiumScreen userProfile={userProfile} onBack={goHome} onOpenDictionarySetup={() => onRouteChange('setup')} onTestUnlockPremium={onTestUnlockPremium || (() => undefined)} />, account_mode_setup: userProfile.accountMode ? homeScreen : <AccountModeSetupScreen onSelectMode={onSelectAccountMode} />, family_setup: <FamilySetupScreen onCreateChild={onCreateChild} onComplete={onChildSetupComplete} onBackHome={goHome} />, character_onboarding: isParentAccount ? <CharacterOnboardingScreen onComplete={onCharacterOnboardingComplete} /> : homeScreen, landing: homeScreen,
    setup: <SetupScreen selectedPlayMode={selectedPlayMode} settings={settings} customDictionaryWords={userProfile.customDictionaryEn} setupError={setupError} isUploadingDictionary={dictionaryUpload.isUploadingDictionary} isAuthenticated={isAuthenticated} userProfile={userProfile} onSettingsChange={onSettingsChange} onFileUpload={dictionaryUpload.onFileUpload} onOpenDictionaryStudio={openDictionaryFromGameArea} onOpenPremium={() => onRouteChange('premium')} onStartGame={startSelectedMode} onBack={goHome} onLogin={onOpenLogin} />, game: <ClassicGameScreen gameState={classicGame.gameState} settings={settings} userProfile={userProfile} isAuthenticated={isAuthenticated} keyStatuses={classicGame.keyStatuses} shakeRowIndex={classicGame.shakeRowIndex} onChar={classicGame.handleChar} onDelete={classicGame.handleDelete} onEnter={classicGame.handleEnter} onHint={classicGame.fetchHint} onRestart={classicGame.startNewGame} onBackHome={goHome} onRegister={onOpenRegister} onDictionaryPeek={onDictionaryPeek} />, profile: <ProfileScreen userProfile={userProfile} isAuthenticated={isAuthenticated} activeDictionaryName={activeDictionaryName} activeDictionaryWordCount={dictionaryWordCount} onBackHome={goHome} onOpenShop={() => isParentAccount ? onRouteChange('shop') : onRouteChange('landing')} onOpenPetRoom={() => isParentAccount ? onRouteChange('pet_room') : onRouteChange('landing')} onLogin={onOpenLogin} />,
    anagrams: <AnagramsScreen words={modeWords} wordLength={settings.wordLength} dictionaryLabel={activeDictionaryName} dictionaryIcon={activeDictionaryIcon} userProfile={userProfile} onGameReward={onGameReward} onWordPractice={onWordPractice} onBackHome={goHome} onDictionaryPeek={onDictionaryPeek} />, sprint: <SprintScreen words={modeWords} wordLength={settings.wordLength} dictionaryLabel={activeDictionaryName} dictionaryIcon={activeDictionaryIcon} userProfile={userProfile} onGameReward={onGameReward} onWordPractice={onWordPractice} onBackHome={goHome} onDictionaryPeek={onDictionaryPeek} />, memory: <MemoryScreen words={modeWords} wordLength={settings.wordLength} dictionaryLabel={activeDictionaryName} dictionaryIcon={activeDictionaryIcon} userProfile={userProfile} onGameReward={onGameReward} onBackHome={goHome} onDictionaryPeek={onDictionaryPeek} />, hangman: <HangmanScreen words={modeWords} wordLength={settings.wordLength} dictionaryLabel={activeDictionaryName} dictionaryIcon={activeDictionaryIcon} userProfile={userProfile} onGameReward={onGameReward} onWordPractice={onWordPractice} onBackHome={goHome} onDictionaryPeek={onDictionaryPeek} />, shop: isParentAccount ? <Shop userProfile={userProfile} onBuy={onBuy} onClose={goHome} onOpenPetRoom={() => onRouteChange('pet_room')} /> : homeScreen, pet_room: isParentAccount ? <PetRoom userProfile={userProfile} onUseItem={onUseItem} onBuy={onBuy} onUpdatePet={onUpdatePet} onClose={goHome} onOpenShop={() => onRouteChange('shop')} /> : homeScreen,
  };
  return <AppRouter route={route} screens={screens} fallback={screens.landing} />;
};
