import React, { useState } from 'react';
import { AppRouter } from './AppRouter';
import { ModeEntryScreen } from './screens/ModeEntryScreen';
import { LandingMixScreen } from './screens/LandingMixScreen';
import { PracticeHomeScreenWithLetterSquare as PracticeHomeScreen } from './screens/PracticeHomeScreenWithLetterSquare';
import { PremiumScreen } from './screens/PremiumScreen';
import { PremiumSuccessScreen } from './screens/PremiumSuccessScreen';
import { KidsHomeScreen } from './screens/KidsHomeScreen';
import { TeacherDashboardScreen } from './screens/TeacherDashboardScreen';
import { SetupScreen } from './screens/SetupScreen';
import { ClassicGameScreen } from './screens/ClassicGameScreen';
import { ProfileScreen } from './screens/ProfileScreen';
import { AccountModeSetupScreen } from './screens/AccountModeSetupScreen';
import { CharacterOnboardingScreen } from './screens/CharacterOnboardingScreen';
import { FamilySetupScreen } from './screens/FamilySetupScreen';
import { AdminControlCenterScreen } from './screens/AdminControlCenterScreen';
import { AdultRoomScreen } from './screens/AdultRoomScreen';
import { DictionarySettingsScreen } from './screens/DictionarySettingsScreen';
import { DictionaryStudioScreen } from './screens/DictionaryStudioScreen';
import { AnagramsScreen, HangmanScreen, MemoryScreen, SprintScreen, TranslationChoiceScreen } from './screens/ModeScreens';
import { GameModeShell } from './screens/GameModeShell';
import { hasSavedAnagramSession } from './AnagramGame';
import { LetterSquareGameV3 } from './LetterSquareGameV3';
import { Shop } from './Shop';
import { PetRoom } from './PetRoom';
import { ClientEntryPath } from '../services/clientEntryPath';
import { AccountMode, DailyQuestCompletionReward, DailyQuestState, GameSettings, GameState, CharStatus, PetState, ShopItem, UserProfile, ViewState, WordLength } from '../types';
import { GameRewardInput } from '../services/gamificationRules';
import { WordPracticeResult } from '../services/gameSessionEngine';
import { PremiumDictionaryDraft } from '../services/premiumDictionaryService';
import { ChildSetupResult } from '../services/familyAccountService';
import { getDailyQuestPrimaryMode } from '../services/dailyQuest';
import { getKidsDictionaryMeta } from '../services/kidsDictionaryCatalog';
import { getPremiumDictionaryMeta } from '../services/premiumDictionaryCatalog';

export type PlayableModeRoute = 'game' | 'anagrams' | 'translation' | 'sprint' | 'memory' | 'hangman' | 'letter_square';
export interface ClassicGameScreenBindings { setupError: string | null; gameState: GameState; keyStatuses: Record<string, CharStatus>; shakeRowIndex: number | null; hasActiveGame?: boolean; resumeGame?: () => boolean; startNewGame: () => void; handleChar: (char: string) => void; handleDelete: () => void; handleEnter: () => void | Promise<void>; fetchHint: () => void | Promise<void>; }
export interface DictionaryUploadBindings { isUploadingDictionary: boolean; error: string | null; onFileUpload: (event: React.ChangeEvent<HTMLInputElement>) => void; }
export interface AppScreensProps { route: ViewState; entryPath: ClientEntryPath; userProfile: UserProfile; isAuthenticated: boolean; dailyQuest?: DailyQuestState | null; dailyQuestReward?: DailyQuestCompletionReward | null; onCloseDailyQuestReward?: () => void; settings: GameSettings; modeWords: string[]; activeDictionaryWordCount?: number; selectedPlayMode: PlayableModeRoute; classicGame: ClassicGameScreenBindings; dictionaryUpload: DictionaryUploadBindings; onRouteChange: (route: ViewState) => void; onEntryPathChange: (entryPath: ClientEntryPath) => void; onSelectedPlayModeChange: (mode: PlayableModeRoute) => void; onSettingsChange: (settings: GameSettings | ((prev: GameSettings) => GameSettings)) => void; onOpenLogin: () => void; onOpenRegister: () => void; onOpenRules: () => void; onBuy: (item: ShopItem) => Promise<void>; onUseItem: (itemId: string) => Promise<void>; onUpdatePet: (pet: PetState) => Promise<void>; onSaveDictionary: (draft: PremiumDictionaryDraft) => Promise<void>; onSelectAccountMode: (mode: AccountMode) => Promise<void>; onCreateChild: (childName: string, pin: string) => Promise<ChildSetupResult>; onChildSetupComplete: (result: ChildSetupResult) => void; onGameReward: (input: GameRewardInput) => Promise<void>; onWordPractice?: (word: string, result: WordPracticeResult) => Promise<void>; onCharacterOnboardingComplete: (character: PetState) => Promise<void>; onGameStarted?: (mode: PlayableModeRoute) => void; onTestUnlockPremium?: () => void; onDictionaryPeek?: () => boolean | Promise<boolean>; }
const WORD_LENGTHS: WordLength[] = [4, 5, 6];
const randomWordLength = (): WordLength => WORD_LENGTHS[Math.floor(Math.random() * WORD_LENGTHS.length)];
const ownWordList = (profile: UserProfile): string[] => Array.from(new Set([...(profile.customDictionaryEn || []), ...(profile.assignedWords || [])]));
export const AppScreens: React.FC<AppScreensProps> = ({ route, entryPath, userProfile, isAuthenticated, dailyQuest, dailyQuestReward, onCloseDailyQuestReward, settings, modeWords, activeDictionaryWordCount, selectedPlayMode, classicGame, dictionaryUpload, onRouteChange, onEntryPathChange, onSelectedPlayModeChange, onSettingsChange, onOpenLogin, onOpenRegister, onOpenRules, onBuy, onUseItem, onUpdatePet, onSaveDictionary, onSelectAccountMode, onCreateChild, onChildSetupComplete, onGameReward, onWordPractice, onCharacterOnboardingComplete, onGameStarted, onTestUnlockPremium, onDictionaryPeek }) => {
  const [premiumReturnTo, setPremiumReturnTo] = useState<ViewState>('landing');
  const ownWords = ownWordList(userProfile);
  const goHome = () => onRouteChange('landing'); const openEntry = (path: ClientEntryPath) => { onEntryPathChange(path); onRouteChange('landing'); }; const startRegisterFor = (path: 'practice' | 'kids') => { openEntry(path); onOpenRegister(); }; const isParentAccount = userProfile.role === 'parent' || userProfile.accountMode === 'parent'; const isTeacher = userProfile.role === 'teacher' || userProfile.accountMode === 'teacher'; const isPractice = isAuthenticated && !isParentAccount && !isTeacher;
  const openPremiumFrom = (from: ViewState) => { setPremiumReturnTo(from); onRouteChange('premium'); };
  const returnFromPremium = () => onRouteChange(premiumReturnTo || 'landing');
  const openDictionaryFromGameArea = () => onRouteChange(isParentAccount ? 'adult_room' : 'dictionary_studio'); const setupError = classicGame.setupError || dictionaryUpload.error; const hasActiveClassicGame = Boolean(classicGame.hasActiveGame); const hasActiveAnagramGame = isAuthenticated && hasSavedAnagramSession(userProfile.username);
  const premiumMeta = isParentAccount ? getKidsDictionaryMeta(settings.activePremiumDictionaryId) : getPremiumDictionaryMeta(settings.activePremiumDictionaryId); const activeDictionaryName = settings.dictionarySource === 'custom' || settings.useCustomDictionary ? 'Слова из вашего списка' : settings.dictionarySource === 'premium' ? premiumMeta.title : isParentAccount ? 'Детский словарь' : 'General English'; const activeDictionaryIcon = settings.dictionarySource === 'custom' || settings.useCustomDictionary ? '📖' : settings.dictionarySource === 'premium' ? premiumMeta.icon : isParentAccount ? '🌈' : '📚'; const dictionaryWordCount = activeDictionaryWordCount ?? modeWords.length;
  const openSetupFor = (mode: PlayableModeRoute) => { if (isTeacher) return; if (mode === 'anagrams' && hasActiveAnagramGame) { onSelectedPlayModeChange(mode); onRouteChange('anagrams'); return; } onSelectedPlayModeChange(mode); onRouteChange('setup'); };
  const startSelectedMode = () => { onGameStarted?.(selectedPlayMode); if (selectedPlayMode === 'game') { classicGame.startNewGame(); return; } onRouteChange(selectedPlayMode); };
  const startDailyQuest = (quest: DailyQuestState) => { const mode = getDailyQuestPrimaryMode(quest); onSelectedPlayModeChange(mode); onSettingsChange(previous => ({ ...previous, wordLength: randomWordLength() })); onRouteChange('setup'); };
  const gameProps = { words: modeWords, wordLength: settings.wordLength, dictionaryLabel: activeDictionaryName, dictionaryIcon: activeDictionaryIcon, userProfile, onGameReward, onWordPractice, onBackHome: goHome, onDictionaryPeek };
  const landingMix = <LandingMixScreen onLogin={onOpenLogin} onStartPractice={() => startRegisterFor('practice')} onStartKids={() => startRegisterFor('kids')} />;
  const practiceEntry = <ModeEntryScreen entryPath="practice" isAuthenticated={isAuthenticated} onLogin={onOpenLogin} onRegister={onOpenRegister} onBackHome={() => openEntry('home')} />;
  const kidsEntry = <ModeEntryScreen entryPath="kids" isAuthenticated={isAuthenticated} onLogin={onOpenLogin} onRegister={onOpenRegister} onBackHome={() => openEntry('home')} />;
  const teacherEntry = <ModeEntryScreen entryPath="teacher" isAuthenticated={isAuthenticated} onLogin={onOpenLogin} onRegister={onOpenRegister} onBackHome={() => openEntry('home')} />;
  const practiceHome = <PracticeHomeScreen userProfile={userProfile} dailyQuest={dailyQuest} dailyQuestReward={dailyQuestReward} onCloseDailyQuestReward={onCloseDailyQuestReward} onStartDailyQuest={startDailyQuest} hasActiveClassicGame={hasActiveClassicGame} hasActiveAnagramGame={hasActiveAnagramGame} activeDictionaryName={activeDictionaryName} activeDictionaryWordCount={dictionaryWordCount} onStartClassic={() => openSetupFor('game')} onStartAnagrams={() => openSetupFor('anagrams')} onStartTranslation={() => openSetupFor('translation')} onStartSprint={() => openSetupFor('sprint')} onStartHangman={() => openSetupFor('hangman')} onStartMemory={() => openSetupFor('memory')} onStartLetterSquare={() => openSetupFor('letter_square')} onOpenProfile={() => onRouteChange('profile')} onOpenDictionaryStudio={() => onRouteChange('dictionary_settings')} onOpenPremium={() => openPremiumFrom('landing')} />;
  const kidsHome = <KidsHomeScreen userProfile={userProfile} dailyQuest={dailyQuest} dailyQuestReward={dailyQuestReward} onCloseDailyQuestReward={onCloseDailyQuestReward} onStartDailyQuest={startDailyQuest} hasActiveClassicGame={hasActiveClassicGame} hasActiveAnagramGame={hasActiveAnagramGame} onStartClassic={() => openSetupFor('game')} onStartAnagrams={() => openSetupFor('anagrams')} onStartTranslation={() => openSetupFor('translation')} onStartSprint={() => openSetupFor('sprint')} onStartHangman={() => openSetupFor('hangman')} onStartMemory={() => openSetupFor('memory')} onStartLetterSquare={() => openSetupFor('letter_square')} onOpenShop={() => onRouteChange('shop')} onOpenProfile={() => onRouteChange('profile')} onOpenPetRoom={() => onRouteChange('pet_room')} onOpenAdultRoom={() => onRouteChange('adult_room')} onOpenPremium={() => openPremiumFrom('landing')} />;
  const teacherHome = <TeacherDashboardScreen userProfile={userProfile} onOpenDictionaryStudio={() => onRouteChange('dictionary_studio')} onOpenAdultRoom={() => onRouteChange('adult_room')} onOpenProfile={() => onRouteChange('profile')} />;
  const roleHomeScreen = isTeacher ? teacherHome : isParentAccount ? kidsHome : isPractice ? practiceHome : practiceEntry;
  const isPublicLandingEntry = entryPath === 'home' || entryPath === 'landing_mix';
  const homeScreen = isPublicLandingEntry ? (isAuthenticated ? roleHomeScreen : landingMix) : entryPath === 'practice' ? (isPractice ? practiceHome : practiceEntry) : entryPath === 'kids' ? (isParentAccount ? kidsHome : kidsEntry) : entryPath === 'teacher' ? (isTeacher ? teacherHome : teacherEntry) : roleHomeScreen;
  const letterSquareRules = ['Соединяйте соседние буквы, чтобы собрать слово змейкой.', 'Диагонали запрещены: только вверх, вниз, влево и вправо.', 'Ошибочные слова попадают в повторение.'];
  const screens: Partial<Record<ViewState, React.ReactNode>> = {
    admin: <AdminControlCenterScreen userProfile={userProfile} onBackHome={goHome} />, adult_room: <AdultRoomScreen userProfile={userProfile} onBackHome={goHome} onOpenDictionaryStudio={() => onRouteChange(isParentAccount ? 'dictionary_settings' : 'dictionary_studio')} />, dictionary_settings: <DictionarySettingsScreen settings={settings} userProfile={userProfile} customDictionaryWords={ownWords} isAuthenticated={isAuthenticated} onSettingsChange={onSettingsChange} onOpenDictionaryStudio={() => onRouteChange('dictionary_studio')} onOpenPremium={() => openPremiumFrom('dictionary_settings')} onBack={goHome} />, dictionary_studio: <DictionaryStudioScreen userProfile={userProfile} onBack={() => onRouteChange(isParentAccount || isTeacher ? 'adult_room' : 'dictionary_settings')} onSaveDictionary={onSaveDictionary} />, premium: <PremiumScreen userProfile={userProfile} onBack={returnFromPremium} onOpenDictionarySetup={() => onRouteChange('dictionary_settings')} onTestUnlockPremium={onTestUnlockPremium || (() => undefined)} />, premium_success: <PremiumSuccessScreen userProfile={userProfile} onPrimaryAction={returnFromPremium} onBackHome={goHome} />, account_mode_setup: userProfile.accountMode ? homeScreen : <AccountModeSetupScreen onSelectMode={onSelectAccountMode} />, family_setup: <FamilySetupScreen onCreateChild={onCreateChild} onComplete={onChildSetupComplete} onBackHome={goHome} />, character_onboarding: isParentAccount ? <CharacterOnboardingScreen onComplete={onCharacterOnboardingComplete} onOpenPremium={() => openPremiumFrom('character_onboarding')} /> : homeScreen, landing: homeScreen,
    setup: <SetupScreen selectedPlayMode={selectedPlayMode} settings={settings} customDictionaryWords={ownWords} setupError={setupError} isUploadingDictionary={dictionaryUpload.isUploadingDictionary} isAuthenticated={isAuthenticated} userProfile={userProfile} questContext={dailyQuest} hasActiveClassicGame={hasActiveClassicGame} onResumeClassicGame={classicGame.resumeGame} onSettingsChange={onSettingsChange} onFileUpload={dictionaryUpload.onFileUpload} onOpenDictionaryStudio={openDictionaryFromGameArea} onOpenPremium={() => openPremiumFrom('setup')} onStartGame={startSelectedMode} onBack={goHome} onLogin={onOpenLogin} />, game: <ClassicGameScreen gameState={classicGame.gameState} settings={settings} userProfile={userProfile} isAuthenticated={isAuthenticated} keyStatuses={classicGame.keyStatuses} shakeRowIndex={classicGame.shakeRowIndex} dictionaryWords={modeWords} dictionaryLabel={activeDictionaryName} dictionaryIcon={activeDictionaryIcon} onChar={classicGame.handleChar} onDelete={classicGame.handleDelete} onEnter={classicGame.handleEnter} onHint={classicGame.fetchHint} onRestart={classicGame.startNewGame} onBackHome={goHome} onRegister={onOpenRegister} onDictionaryPeek={onDictionaryPeek} />, profile: <ProfileScreen userProfile={userProfile} isAuthenticated={isAuthenticated} activeDictionaryName={activeDictionaryName} activeDictionaryWordCount={dictionaryWordCount} onBackHome={goHome} onOpenShop={() => isParentAccount ? onRouteChange('shop') : onRouteChange('landing')} onOpenPetRoom={() => isParentAccount ? onRouteChange('pet_room') : onRouteChange('landing')} onLogin={onOpenLogin} />,
    anagrams: <AnagramsScreen {...gameProps} />, translation: <TranslationChoiceScreen {...gameProps} />, sprint: <SprintScreen {...gameProps} />, memory: <MemoryScreen {...gameProps} />, hangman: <HangmanScreen {...gameProps} />, letter_square: <GameModeShell title="Змейка" subtitle="Соединяй буквы цепочкой" rules={letterSquareRules} dictionaryWords={modeWords} dictionaryLabel={activeDictionaryName} dictionaryIcon={activeDictionaryIcon} wordLength={settings.wordLength} onBackHome={goHome} onDictionaryPeek={onDictionaryPeek}><LetterSquareGameV3 userProfile={{ ...userProfile, customDictionaryEn: modeWords }} onGameReward={onGameReward} onWordPractice={onWordPractice} onBack={goHome} /></GameModeShell>, shop: isParentAccount ? <Shop userProfile={userProfile} onBuy={onBuy} onClose={goHome} onOpenPetRoom={() => onRouteChange('pet_room')} /> : homeScreen, pet_room: isParentAccount ? <PetRoom userProfile={userProfile} onUseItem={onUseItem} onBuy={onBuy} onUpdatePet={onUpdatePet} onClose={goHome} onOpenShop={() => onRouteChange('shop')} /> : homeScreen,
  };
  return <AppRouter route={route} screens={screens} fallback={screens.landing} />;
};
