import React, { useEffect, useRef, useState } from 'react';
import { motion } from 'motion/react';
import { DailyQuestCompletionReward, DailyQuestState } from '../types';
import { getShopImageUrl } from '../services/petAssets';
import { getWorld } from '../services/premiumFeatureCatalog';

const MYSTERY_BOX_IMAGE = '/assets/rewards/mystery-box.webp';
const T = {
  hours: 'ч', minutes: 'мин', quest: 'Ежедневное испытание', petTask: 'Задание от питомца', practiceTask: 'Ежедневная практика', done: 'Выполнено', progress: 'Прогресс', openBg: 'Открыт фон', newBg: 'Награда: новый фон', boxOpen: 'Секретная коробка открыта', boxReward: 'Награда: секретная коробка', chooseRoom: 'Можно выбрать в комнате питомца', randomTreat: 'Внутри случайное лакомство', daysInRow: 'Продлевает дни подряд и сохраняется в статистике', play: 'Играть', questDone: 'Задание выполнено', bgOpened: 'Новый фон открыт!', box: 'Секретная коробка!', invite: 'Питомец приглашает вас в новое место.', prepared: 'Питомец приготовил награду за сегодняшнее испытание.', roomBg: 'Фон комнаты', gotTreat: 'Выпало лакомство', reward: 'Награда', great: 'Здорово!', petRoom: 'В комнату питомца', shop: 'В магазин', viewReward: 'Посмотреть награду', rewardReceived: 'Награда получена'
};
const londonDateKey = (date: Date): string => new Intl.DateTimeFormat('en-CA', { timeZone: 'Europe/London', year: 'numeric', month: '2-digit', day: '2-digit' }).format(date);
const getDailyQuestCountdown = (): string => { const now = new Date(); const key = londonDateKey(now); let min = 1; for (; min <= 1500; min += 1) if (londonDateKey(new Date(now.getTime() + min * 60000)) !== key) break; return String(Math.floor(min / 60)) + ' ' + T.hours + ' ' + String(min % 60).padStart(2, '0') + ' ' + T.minutes; };

export const DailyQuestCard: React.FC<{ quest: DailyQuestState; onStart?: (quest: DailyQuestState) => void; variant?: 'kids' | 'practice'; onOpenPetRoom?: () => void; onOpenShop?: () => void }> = ({ quest, onStart, variant = 'kids', onOpenPetRoom, onOpenShop }) => {
  const [countdown, setCountdown] = useState(getDailyQuestCountdown);
  const world = quest.rewardWorldId ? getWorld(quest.rewardWorldId) : null;
  const isPractice = variant === 'practice';
  const hasKnownReward = Boolean(world || quest.rewardItemId);
  useEffect(() => { setCountdown(getDailyQuestCountdown()); const timerId = window.setInterval(() => setCountdown(getDailyQuestCountdown()), 60000); return () => window.clearInterval(timerId); }, []);
  const openRewardTarget = () => { if (isPractice) return; if (world || quest.rewardItemId) onOpenPetRoom?.(); else onOpenShop?.(); };
  return <section className="mt-5 rounded-3xl border-2 border-purple-100 bg-purple-50/60 p-4 text-left sm:p-5" aria-label={T.quest}><div className="flex items-start justify-between gap-3"><div><p className="text-[11px] font-black uppercase tracking-widest text-purple-500">{isPractice ? T.practiceTask : T.petTask}</p><h2 className="mt-1 text-lg font-black text-indigo-950">{quest.title}</h2></div><div className={`shrink-0 rounded-full px-3 py-1 text-xs font-black ${quest.completed ? 'bg-green-100 text-green-700' : 'bg-white text-purple-700'}`}>{quest.completed ? T.done : countdown}</div></div><p className="mt-2 text-sm font-bold leading-relaxed text-gray-600">{quest.description}</p>{quest.kind === 'all_five_games' && !quest.completed && <p className="mt-2 text-xs font-black text-purple-700">{T.progress}: {quest.progressLabel}</p>}<div className="mt-4 flex items-center gap-3 rounded-2xl bg-white px-3 py-2.5">{isPractice ? <span className="text-2xl" aria-hidden="true">★</span> : world ? <span className="text-2xl" aria-hidden="true">{world.emoji}</span> : <img src={MYSTERY_BOX_IMAGE} alt="" aria-hidden="true" className="h-10 w-10 object-contain" draggable={false} />}<div className="min-w-0 flex-1 text-sm font-bold text-indigo-900">{isPractice ? (quest.completed ? 'Дни подряд продлены' : 'Задание на дни подряд') : world ? `${quest.completed ? T.openBg : T.newBg} · ${world.title}` : quest.completed ? T.boxOpen : T.boxReward}<div className="text-xs font-bold text-gray-500">{isPractice ? T.daysInRow : quest.completed ? (hasKnownReward ? T.rewardReceived : 'Коробка уже засчитана. Следующее задание — завтра.') : world ? T.chooseRoom : T.randomTreat}</div></div>{!quest.completed && onStart && <button type="button" onClick={() => onStart(quest)} className="shrink-0 rounded-xl bg-purple-600 px-4 py-2 text-sm font-black text-white shadow-sm transition hover:bg-purple-700">{T.play}</button>}{quest.completed && !isPractice && <button type="button" onClick={openRewardTarget} className="shrink-0 rounded-xl bg-green-50 px-3 py-2 text-xs font-black text-green-700 transition hover:bg-green-100">{hasKnownReward ? T.viewReward : T.petRoom}</button>}</div></section>;
};

export const DailyQuestRewardModal: React.FC<{ reward: DailyQuestCompletionReward; onClose: () => void; onOpenPetRoom?: () => void; onOpenShop?: () => void }> = ({ reward, onClose, onOpenPetRoom, onOpenShop }) => {
  const dialogRef = useRef<HTMLDivElement>(null);
  const world = reward.worldId ? getWorld(reward.worldId) : null;
  const imageUrl = reward.item ? getShopImageUrl(reward.item) : null;
  useEffect(() => {
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    const focusTimer = window.setTimeout(() => dialogRef.current?.focus(), 0);
    const onKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); };
    window.addEventListener('keydown', onKeyDown);
    return () => { window.clearTimeout(focusTimer); document.body.style.overflow = previousOverflow; window.removeEventListener('keydown', onKeyDown); };
  }, [onClose]);
  const goPetRoom = () => { onClose(); onOpenPetRoom?.(); };
  const goShop = () => { onClose(); onOpenShop?.(); };
  return <div className="fixed inset-0 z-[95] flex items-center justify-center bg-indigo-950/45 px-4 backdrop-blur-sm" role="presentation"><motion.div ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="daily-quest-reward-title" aria-describedby="daily-quest-reward-description" tabIndex={-1} initial={{ opacity: 0, scale: 0.96 }} animate={{ opacity: 1, scale: 1 }} className="w-full max-w-sm rounded-[2rem] border-2 border-purple-100 bg-white p-6 text-center shadow-2xl outline-none"><div className="mb-3 inline-flex rounded-full bg-purple-50 px-4 py-1 text-xs font-black uppercase tracking-widest text-purple-700">{T.questDone}</div>{world ? <div className="text-5xl" aria-hidden="true">{world.emoji}</div> : <img src={MYSTERY_BOX_IMAGE} alt="" aria-hidden="true" className="mx-auto h-16 w-16 object-contain" draggable={false} />}<h2 id="daily-quest-reward-title" className="mt-2 text-2xl font-black text-indigo-950">{world ? T.bgOpened : T.box}</h2><p id="daily-quest-reward-description" className="mt-2 text-sm font-bold text-gray-500">{world ? T.invite : T.prepared}</p><motion.div initial={{ scale: 0.75, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} transition={{ delay: 0.18 }} className={`mx-auto mt-5 flex h-32 w-32 items-center justify-center rounded-3xl border-2 border-indigo-50 ${world ? `bg-gradient-to-b ${world.backgroundClass}` : 'bg-indigo-50/50'}`}>{world ? <span className="text-6xl">{world.emoji}</span> : imageUrl && reward.item ? <img src={imageUrl} alt={reward.item.name} className="h-28 w-28 object-contain" /> : <span className="text-6xl">*</span>}</motion.div><div className="mt-4 text-xs font-black uppercase tracking-widest text-purple-500">{world ? T.roomBg : T.gotTreat}</div><div className="mt-1 text-xl font-black text-indigo-950">{world?.title || reward.item?.name || T.reward}</div><div className="mt-6 grid gap-2"><button type="button" onClick={goPetRoom} className="w-full rounded-2xl bg-indigo-600 px-5 py-3 font-black text-white">{world ? T.petRoom : 'Использовать лакомство'}</button>{onOpenShop && <button type="button" onClick={goShop} className="w-full rounded-2xl border-2 border-indigo-100 bg-white px-5 py-3 font-black text-indigo-700">{T.shop}</button>}<button type="button" onClick={onClose} className="w-full rounded-2xl bg-indigo-50 px-5 py-3 font-black text-indigo-700">{T.great}</button></div></motion.div></div>;
};
